language: generic
sudo: required
services:
    - docker

# commands executed before tests are run
before_install:
    - docker build -t ci-cd-test -f Dockerfile.dev . 

script:
    - docker run -e CI=true ci-cd-test npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-563355306919"
    bucket_path: "docker"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY